#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
#yabai -m config debug_output on

# General settings
yabai -m config focus_follows_mouse autofocus
yabai -m config window_placement first_child
yabai -m config window_placement second_child

yabai -m rule --add app="^Firefox$" manage=on
