git: 
    paging:
        colorArg: always
        pager: delta --dark --paging=never --syntax-theme base16-256 --diff-so-fancy
        useConfig: false
    autoFetch: false
gui:
  nerdFontsVersion: 3
