import = ["~/.config/alacritty/themes/gruvbox_material_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[window]
opacity = 0.95
option_as_alt = "Both"
dynamic_padding = true
decorations= "Buttonless"

[window.padding]
x = 2
y = 2
