import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight"

[window]
opacity = 1
blur = false
option_as_alt = "Both"
dynamic_padding = true
decorations= "Buttonless"

[window.padding]
x = 2
y = 2
